server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: uber_ride_group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    url: jdbc:mysql://localhost:3306/uberdb?useSSL=false&serverTimezone=UTC
    username: root
    password: Deepu@2003

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  topic:
    name: uber-ride-topic
